---
# PostgreSQL vars for Debian 13 (Trixie)

postgresql_service_name: "postgresql"

postgresql_bin_directory: /usr/bin

# Modern signed-by repository definition
postgresql_apt_repository: "deb [signed-by=/etc/apt/trusted.gpg.d/postgresql.asc] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main {{ postgresql_version }}"

postgresql_fdw_mysql_packages: "postgresql-{{ postgresql_version }}-mysql-fdw"
postgresql_fdw_ogr_packages: "postgresql-{{ postgresql_version }}-ogr-fdw"
