---
galaxy_info:
  author: neox5
  description: Manage APT repository configuration for Debian systems
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - "13"

  galaxy_tags:
    - system
    - apt
    - repositories

dependencies: []
