---
# Restic installation tasks

- name: Create restic directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ restic_download_path }}/bin"
    - "{{ restic_script_dir }}"
    - "{{ restic_log_dir }}"

- name: Download restic binary
  ansible.builtin.get_url:
    url: "{{ restic_url }}"
    dest: "{{ restic_download_path }}/restic_{{ restic_version }}_linux_amd64.bz2"
    mode: "0644"
  register: restic_download

- name: Extract restic binary
  ansible.builtin.shell:
    cmd: "bunzip2 -c {{ restic_download_path }}/restic_{{ restic_version }}_linux_amd64.bz2 > {{ restic_download_path }}/bin/restic-{{ restic_version }}"
    creates: "{{ restic_download_path }}/bin/restic-{{ restic_version }}"
  when: restic_download.changed

- name: Set restic binary permissions
  ansible.builtin.file:
    path: "{{ restic_download_path }}/bin/restic-{{ restic_version }}"
    owner: root
    group: root
    mode: "0755"

- name: Create restic symlink
  ansible.builtin.file:
    src: "{{ restic_download_path }}/bin/restic-{{ restic_version }}"
    dest: "{{ restic_install_path }}/restic"
    state: link
    owner: root
    group: root
