#ENC[AES256_GCM,data:Vhp9ycx1VzhzTWcanou5wNME38bF++6WCrOiT7/eLV49tkg=,iv:FvhGy+JsR3T37aXWxNyqoKHnv5WgDjV3uV6lyneZqbs=,tag:dEwd0QD8JfvNpvtcLQuWLg==,type:comment]
#ENC[AES256_GCM,data:L+MIjHJqij9qal8v7JK5PNJUWmUqvA==,iv:n+zYuSn87/vMv67kpQSD0I4I2pl6J2xgbTu+3vqyHuw=,tag:KalNmKcG5gGDqHb8plLcWQ==,type:comment]
n8n_db_password: ENC[AES256_GCM,data:ZvS5n4yeg0CSyuEjv6vH11HP7Xp3HBXfUCq8PCOZkY3Tua6kZT6wzrTEqG+ayC2Sn+ogup4HxfzHR0bPaTycpw==,iv:PHzNUP9x1mMfsUPCg0LURIi4DzDpgj8mVm1mMD6dppg=,tag:2dz3Egn+lVwmWJJGZmeLhg==,type:str]
sops:
    age:
        - recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTURrallQTFM2SkhicDN5
            ekM5QlgvQTJTMHk4UnBaeURNMUgxZVMzWXh3CnNGeGtZYURwVzl6a2c3N29VYjlN
            eEE0QmRzSmUrRFhwZmxzM0NPenk1Q00KLS0tIFRjZ2dORWZyT3cxZEhiTGxlZzBl
            d01nRmhIQTdHVmNhNUNocDFKWDBOemsKzwP86Cj+WEDWmhruQUzWMH7tr+q6UJtU
            O29Y1d/1Cag7fc9QlWvKp2pdsRZpRuioqFnSb+cvFfQ/tEpsICA95Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:45:33Z"
    mac: ENC[AES256_GCM,data:gTLlVfhCWfFTaHkcFP7sbVAMu5YPuilywbvSViqO59RFUaYwvq34aJKs1iIZ/5vmj+hbiKGFBy8oulElCnBF6wzaM4OxBaE0En87/yoT3f4gTPqCcqAltTqTwDMSkvF/1wDv16x2uzxgUb8gUkr7OQvVT0nHyZtrz2lv8KL/6qo=,iv:VgK5vLNg5nEgebW99/rqG9U8+j9W4R2rSwvrrCPUzV8=,tag:GeqBSi4J/4dPVBq7pzYX1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
