#ENC[AES256_GCM,data:NtKTtfYgTM9ZOu5pByj7UMUdTuR0aOgxiYiDtnI=,iv:tT4Fbk5o725TVKPU4EJpjEE/m8Qy3b90cYA5A5CxOvM=,tag:vow4UJzUGhyQQtlcVteqaw==,type:comment]
#ENC[AES256_GCM,data:qFacoXog2MtTpDgOMcSCpLdgmT4Fp/19VEY944fzFKBW4FEew9OznDs78o+4PTOpS4GzsADPE7XnLCtAeKV8WlCRVU/k,iv:EomRNF4z3LulRfotSX+TbvGyP4hRADeFbJIcs7FdYrk=,tag:p2qArzkZQfVT2+DdZxQZ5g==,type:comment]
n8n_db_password: ENC[AES256_GCM,data:ZvS5n4yeg0CSyuEjv6vH11HP7Xp3HBXfUCq8PCOZkY3Tua6kZT6wzrTEqG+ayC2Sn+ogup4HxfzHR0bPaTycpw==,iv:PHzNUP9x1mMfsUPCg0LURIi4DzDpgj8mVm1mMD6dppg=,tag:2dz3Egn+lVwmWJJGZmeLhg==,type:str]
sops:
    age:
        - recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTURrallQTFM2SkhicDN5
            ekM5QlgvQTJTMHk4UnBaeURNMUgxZVMzWXh3CnNGeGtZYURwVzl6a2c3N29VYjlN
            eEE0QmRzSmUrRFhwZmxzM0NPenk1Q00KLS0tIFRjZ2dORWZyT3cxZEhiTGxlZzBl
            d01nRmhIQTdHVmNhNUNocDFKWDBOemsKzwP86Cj+WEDWmhruQUzWMH7tr+q6UJtU
            O29Y1d/1Cag7fc9QlWvKp2pdsRZpRuioqFnSb+cvFfQ/tEpsICA95Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T19:55:25Z"
    mac: ENC[AES256_GCM,data:QhSGr7qAUrbklF35OO0bNQ4AdOczjKozEcHCt77ZXko15WWwNDDVOB7RuX7YaHnp+dEJN4rO66ytl85yjRkD0DGuxZ/YiCRhwLrbhgoXxd0PmX1WpbX1l/njKQR7Fmy6mXCHJyms+DaW7dUva3xIJfN4nSlMpKYNAb3LLYpXZJk=,iv:k8P7o7RCdbuvqABC590GflWISHIrD4n7yv9l+V0gUcM=,tag:AdX5JG6iVt9Qz/O2aTkSLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
