---
galaxy_info:
  role_name: restic
  author: neox5
  description: Restic backup automation for Debian 13 Trixie
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - backup
    - restic
    - systemd

dependencies: []
