---
- name: Configure firewall (firewalld backend)
  import_tasks: firewall_firewalld.yml
  when: security_firewall_backend == "firewalld"

- name: Configure firewall (nftables backend)
  import_tasks: firewall_nftables.yml
  when: security_firewall_backend == "nftables"
