---
- name: Setup automatic updates (dnf-automatic backend)
  import_tasks: updates_dnf_automatic.yml
  when: security_updates_backend == "dnf_automatic"

- name: Setup automatic updates (unattended-upgrades backend)
  import_tasks: updates_unattended_upgrades.yml
  when: security_updates_backend == "unattended_upgrades"
