---
galaxy_info:
  role_name: postgresql
  author: neox5
  description: PostgreSQL 17 deployment for Debian 13 Trixie
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - database
    - postgresql

dependencies: []
