---
galaxy_info:
  author: neox5
  description: Comprehensive security hardening for Debian
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - "13"

  galaxy_tags:
    - security
    - hardening
    - ssh
    - firewall
    - fail2ban
    - journald
    - debian

dependencies: []
