---
galaxy_info:
  author: neox5
  description: Comprehensive security hardening
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Fedora
      versions:
        - "39"
        - "40"

  galaxy_tags:
    - security
    - hardening
    - ssh
    - firewall
    - fail2ban
    - journald
    - fedora

dependencies: []
