---
# Certs role handlers

- name: restart cert-dependent services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop: "{{ certs_reload_services }}"
  failed_when: false
  when: certs_reload_services | length > 0
