---
# PostgreSQL Installation
# Deploys PostgreSQL using custom postgresql role
# Usage: ansible-playbook -i inventory/prod playbooks/postgresql_install.yml

- name: Install and configure PostgreSQL
  hosts: all
  become: yes
  roles:
    - postgresql
