---
# Restic Installation
# Deploys Restic backup system using roles-ansible.restic
# Usage: ansible-playbook -i inventory/lab playbooks/restic_install.yml

- name: Install and configure Restic
  hosts: all
  become: yes
  roles:
    - roles-ansible.restic
