---
- name: Complete system configuration
  hosts: all
  become: yes

  roles:
    - apt_repositories
    - security_hardening

- name: Database servers
  hosts: db
  become: yes

  roles:
    - anxs.postgresql
