testuser_db_password: ENC[AES256_GCM,data:QTEKeu+uUx1hCM8=,iv:0+s3LDou7A7UHxwUU4N4fx65iWwTCjU9MCU02lLftk0=,tag:N1T8P3Z0aX69YlZYyGDvgg==,type:str]
restic_local_password: ENC[AES256_GCM,data:DI0SGC9LUbJf,iv:8zzrcAMuEQULqO4cZvMjc0FXgLfGa9cJAQF0KN6wT9Q=,tag:hFugj6+narg6uSCM/q9tFQ==,type:str]
sops:
    age:
        - recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkg2T3NFSFpyWkhnejhh
            d1dWclA2WnFPaS9kTEQzbUhvV1g0eHp4MG1jCk1kN2FmdlhPN0NxWWFXc0lkL0xP
            d2ZUWk1ybmg0RkVOMGZnNlZVbk9oUmsKLS0tIGdoOHZlNmV1U1JBeHRTeGZ2QWpk
            eHFub2J4UGFOdkkxOHhGMk8rdzI0MG8K8aYf3AEX+ZxTKR4dRgScUVtsz/R82ocI
            +maZLWu1rEBNPyLkVApd+o8ZE/cgU5tD3/3z9A2JleNBMlFSjvpHsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T18:33:46Z"
    mac: ENC[AES256_GCM,data:Wde92CTdK8KL3NU3KQ/0TNQICTnHsJrlPmquxz8OLua49lsfsX8+dEpFjCyciFEj2C6CPf/P4Bpe9wsQJi0wFi/feuxU6OYQOC8uYbS1Dj/clObA3KO9gaSusiiElFG0bfoePZLXBzscWRcZWViuZNrbX65QB7gAdsEBJNVK4FY=,iv:ZVlBBaxA9bcMlenzijwTksp+R544MbqGRlAW6S7fB/Y=,tag:AxrfQ/g7PCjT4O79oN+8FA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
