n8n_db_password_secret: ENC[AES256_GCM,data:8p7eUBpCwrlIzVa9/90x2rxFWk/n6wjVcOv+h9PbHXmdKWy9USXET9fxafCrXk0l1++sUwzzieWbeXAZnBnrFg==,iv:RHbtmBvHhb35CxaTc2IztsjeyLgR34kctmR0IS/OH6g=,tag:Mysd8imVL5P9EN9yMUdz4g==,type:str]
n8n_encryption_key_secret: ENC[AES256_GCM,data:wRBt+wKXMp9TQHJ0CoFT0Hvapl2BJuokWE2S4X2MX/IQUfvB96x/n9ocoBDxyZYnR9Qh8zIjhUumZbQ3vY0wJA==,iv:I9exn/vSpJp//xOc73HQspHrTkfoYLa0OE+peaKmkfM=,tag:s9smmuzSCnFHFMreR6pI3Q==,type:str]
restic_repository_password_secret: ENC[AES256_GCM,data:yskm9nzbpQyqC3YCk6H7O3yTqJYOwbxqnlVoiCa6g/WL/m55bKmJe1eQ95BPzB4/kHsYkA7mdU8vzhQn4yIvXg==,iv:mUkf7vfQJ9rZZDv1bLcyie2yFjXBC90X+KhMNs8/L9U=,tag:AD4SXagzbCJ0Dhjao8lVuw==,type:str]
sops:
    age:
        - recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkg2T3NFSFpyWkhnejhh
            d1dWclA2WnFPaS9kTEQzbUhvV1g0eHp4MG1jCk1kN2FmdlhPN0NxWWFXc0lkL0xP
            d2ZUWk1ybmg0RkVOMGZnNlZVbk9oUmsKLS0tIGdoOHZlNmV1U1JBeHRTeGZ2QWpk
            eHFub2J4UGFOdkkxOHhGMk8rdzI0MG8K8aYf3AEX+ZxTKR4dRgScUVtsz/R82ocI
            +maZLWu1rEBNPyLkVApd+o8ZE/cgU5tD3/3z9A2JleNBMlFSjvpHsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T19:51:12Z"
    mac: ENC[AES256_GCM,data:L+O19ylijWjE6jz3ruoIJqyWBg8I/GM31WRc+qaSgBG/UyRkwyDEpc1vJMhlK62ZOcEpXYNmaUHGzQO6T2BQ7YzFV5b2Fl+TOnQCnlVQ4Uv7Yd+hLby2Iv/bsiBHjO95oWCqg+k3VhP068u2Ns2ni8jGB/nLcwWnZ5T5NyLbebc=,iv:yitioVEdBr4g/ceBCkzzt54WSsmYfDbT7OB0ZYGP0Zc=,tag:YDgzIh5LuKLO/4dX4YBRQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
