testuser_db_password: ENC[AES256_GCM,data:QTEKeu+uUx1hCM8=,iv:0+s3LDou7A7UHxwUU4N4fx65iWwTCjU9MCU02lLftk0=,tag:N1T8P3Z0aX69YlZYyGDvgg==,type:str]
sops:
    age:
        - recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkg2T3NFSFpyWkhnejhh
            d1dWclA2WnFPaS9kTEQzbUhvV1g0eHp4MG1jCk1kN2FmdlhPN0NxWWFXc0lkL0xP
            d2ZUWk1ybmg0RkVOMGZnNlZVbk9oUmsKLS0tIGdoOHZlNmV1U1JBeHRTeGZ2QWpk
            eHFub2J4UGFOdkkxOHhGMk8rdzI0MG8K8aYf3AEX+ZxTKR4dRgScUVtsz/R82ocI
            +maZLWu1rEBNPyLkVApd+o8ZE/cgU5tD3/3z9A2JleNBMlFSjvpHsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T11:16:29Z"
    mac: ENC[AES256_GCM,data:aRTt2qR+IetxQllqaLd+Ktpgat73LSgoXccXmqbJw2qgHQS0aUo7PHC1hOxHZ8123eQPD6GEXkLMxjltk9/IH7QoQFqfHOx97EoDiJMu0qfxQ/KnL/ydTIyKxKwCzCvluq6E7k8uf/Ibv+fJwmnmWSiBHSm8+Or/ShLTdLW64w4=,iv:qnVyb/AP0NB16PcP7W2eWsfjSMnmTauZL4aq4Ssukuc=,tag:b283W3wQFVVjeeJdN+oX9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
